input = "BCDCBADDCCxACCCCDBCCDBDAxBBBBCDBxACAxDCDBACCxDBCBBxABxADBDDDCxxAxADCxBBABBDDBDDADCBDBBCxBxDCxBAxBDDDDAABxADDBBCCBAACDAxDDDAxBBDDDDxBDBCDDxCABCACABDDDACCBCCCDDABxADDDDCCCCDCCxDCABBADBBABDBBDCBDBCAADxxACCxxACADADADBDBDAADCCABAADCxBADBBCxACCBCDADDCADADCCADBDAADBBxxBADDBADDBBxCCDDCCABAAxBDAxCADABDDDBBDADACABCDCCBABACABDCCDDDAABACBxBCCxDDxCCCxADDCxCABxDDBCxBCCCAADxBAADDDBAxCxBBCBBBBADCCDABADAAACACCCBBBxCBDCABABCDxCDAADDDCBCACCCxABDDBAxAAxCAABxAAABDCCADCDxxCADACDADCCBACCCCCDCABCxBAACCACAAADCACCCCDxBCACCDDADxCCBDCxACCDDABCxBDDAAxDCDBBABBxBBDCDCCBAxBBxDxBACDACCACAxBCCACBAxBDAAAxCDACCABDABCBABCCDDAxDBDxCACCBBCAAxBDBBADBAAACADACCBBADACACACxxBCDxDxCABxCCBBDDDCABxxACCDBDDAxDADCDACABCDBCBDCCCDADxDBCABADACBCCDDDCDBCDCxAABDDDACADCBDABxAxCDACADDBBCBBCDBCDACCACBCADxDCABBABCADBBCxxCxDADBACACBCADCCBxBDACDCDCDBBDDCDDBxCCDDDDxCCBCDACBABABBACBACDCDBBDDADDCBCBxCAxDxDAADCCCxDBAxBBCBAACABAxACCBCCCxBBDBxxxCxCCADDCBDCxCACCCDCxAABxDBDBBBBDBBBABACAACCxBDxAAxDCDDDACDADCAAAxADxBBDxCBDDBDCBCDCDACACCxABxACxBCCCCCCDDBxxBBCABBAACDxDDBBDCBxADDAABxDADABACDBBDCBBxxAxAABDBDACxCBABxCADDDBBCDAAxDDAACxDBDCBCBCAADDDCBACCACACADBAADDxBBADAACABAACDBBDAADABCxCABBDBxCABBAADBxABxCABxxBABAxDBCBCDBDxAxDACACBCDCDCDADABDDBCBBAAADCCxDCCBDBBADABCxBCxCABABBCBxBDDDCCCABCBDBDxDBBAAxADxBDAxxBDCABxDAADBBCBBxADABDBADBDBBCAxACADBCDxDCDAxBDDxACDxDCCADDAAAAADCAxACxCCADACAABACBCDBCDBBCABAAADBBACACxDBCCBCDxDACBAAABCADACCBDCDDADABDAxDBDBDAxBDBBBACDCDxCCCDDADCACDADDAABADDBBCBCCBAAACxAxDBDDDxDCBDCBBBAADCAACxBACDCCCxCACCxCDCBACDxCBADCDBABDBBxCBAxCACDxCDBBAAxACAADACxxCCAADCDDABDDDADxBAAABAABDCBCBBDDCxDADxCCCCDAxACDDBCBDCDCCDAABDACDBBBBBxCBABBCDABCBBCBBAABBACCBAACCADBDCAxDDBAAAACCACAABABADDBBCAxADDBAADCCDAACABBBCxDBDDDBCxBABCBABAADDBAxAxCBxCACBBAACDDxxDABDBACCABCDAAACAAABxCDBDCBDBCDABACBCAADBDDDDBBBBDDDDxABCAxDBBCDAxDxCCDDDBCCBCCCCCACDBACCCCBCxDCACCCADBDADBBADBDAABDBAADDDBAxDCAxBCAxADCBDBBxxDABBABBBCBCxADAAxBxxDDxABCCCACDDBABBxABAADACCxxDACCBCDCBCDCCADBCDDADBBAAxADBCADDDAACDAABACxACAABBxDxDDACBADAxBBCACAxADBACDDCCABADCDDBBCxxxBBACCBCDAA"
testInput = "AxBCDDCAxD"
def getHealthPotions(input:str):
    sum = 0
    for i in range(0, len(input), 2):
        pair = input[i:i+2]
        if len(pair) < 2:
            continue

        if not "x" in pair:
           sum += 2 
   
        for char in pair:
            if char == "A":
                sum += 0
                continue

            if char == "B":
                sum += 1
                continue

            if char == "C":
                sum += 3
                continue 

            if char == "D":
                sum += 5
                continue

    return sum



print(getHealthPotions(testInput))
print(getHealthPotions(input))
